/*********************************************************************
  ForgotPassword.js
  Sends the user a password reset email.  Email is generated by
  Firebase.  We just need to supply the email address.
*********************************************************************/
import React, { Component } from 'react';
import firebase from 'firebase';
import { connect } from 'react-redux';
import { Actions } from 'react-native-router-flux';
import { ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { Button, Card, CardSection, Input, Spinner } from '../common';

class ForgotPassword extends Component {
  render() {
    return (
      <View>
        <Text>Hi from ForgotPassword.js</Text>
      </View>
    );
  }
}

export default ForgotPassword;
